from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501

class GetProductById200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, data=None):  # noqa: E501
        """GetProductById200Response - a model defined in OpenAPI

        :param success: The success of this GetProductById200Response.  # noqa: E501
        :type success: bool
        :param data: The data of this GetProductById200Response.  # noqa: E501
        :type data: Product
        """
        self.openapi_types = {
            'success': bool,
            'data': Product
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data'
        }

        self._success = success
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetProductById200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getProductById_200_response of this GetProductById200Response.  # noqa: E501
        :rtype: GetProductById200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this GetProductById200Response.


        :return: The success of this GetProductById200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this GetProductById200Response.


        :param success: The success of this GetProductById200Response.
        :type success: bool
        """

        self._success = success

    @property
    def data(self) -> Product:
        """Gets the data of this GetProductById200Response.


        :return: The data of this GetProductById200Response.
        :rtype: Product
        """
        return self._data

    @data.setter
    def data(self, data: Product):
        """Sets the data of this GetProductById200Response.


        :param data: The data of this GetProductById200Response.
        :type data: Product
        """

        self._data = data
