from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501

class GetAllProducts200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, data=None, total=None):  # noqa: E501
        """GetAllProducts200Response - a model defined in OpenAPI

        :param success: The success of this GetAllProducts200Response.  # noqa: E501
        :type success: bool
        :param data: The data of this GetAllProducts200Response.  # noqa: E501
        :type data: List[Product]
        :param total: The total of this GetAllProducts200Response.  # noqa: E501
        :type total: int
        """
        self.openapi_types = {
            'success': bool,
            'data': List[Product],
            'total': int
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data',
            'total': 'total'
        }

        self._success = success
        self._data = data
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllProducts200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAllProducts_200_response of this GetAllProducts200Response.  # noqa: E501
        :rtype: GetAllProducts200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this GetAllProducts200Response.


        :return: The success of this GetAllProducts200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this GetAllProducts200Response.


        :param success: The success of this GetAllProducts200Response.
        :type success: bool
        """

        self._success = success

    @property
    def data(self) -> List[Product]:
        """Gets the data of this GetAllProducts200Response.


        :return: The data of this GetAllProducts200Response.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this GetAllProducts200Response.


        :param data: The data of this GetAllProducts200Response.
        :type data: List[Product]
        """

        self._data = data

    @property
    def total(self) -> int:
        """Gets the total of this GetAllProducts200Response.


        :return: The total of this GetAllProducts200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this GetAllProducts200Response.


        :param total: The total of this GetAllProducts200Response.
        :type total: int
        """

        self._total = total
